import { orange, purple, volcano, yellow, blue, green, red } from '@ant-design/colors';

export const lineColors = [
    orange[5],
    blue[3],
    green[3],
    volcano[3],
    yellow[5],
    blue[2],
    orange[6],
    green[5],
    purple[3],
    blue[5],
    orange[6],
    blue[5],
    green[2],
    volcano[2],
    yellow[6],
    blue[3],
    orange[7],
    green[7],
    purple[7],
    blue[3],
    red[4],
];
